# Generated by Django 3.0.8 on 2020-07-13 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='hotel', max_length=30)),
                ('daily_cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('address', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='hotels')),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_location', to='core.County')),
            ],
        ),
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='attractions')),
                ('county', models.ManyToManyField(related_name='attraction_hotels', to='core.Hotel')),
            ],
        ),
    ]
