# Generated by Django 3.0.8 on 2020-07-13 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='hotel',
            field=models.ManyToManyField(related_name='attraction_hotels', to='core.Hotel'),
        ),
        migrations.RemoveField(
            model_name='attraction',
            name='county',
        ),
        migrations.AddField(
            model_name='attraction',
            name='county',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='attraction_location', to='core.County'),
            preserve_default=False,
        ),
    ]
